// Generated by CoffeeScript 1.9.1
var cache, extend, layers;

extend = require('extend');

layers = require('odo-layers');

cache = require('odoql-exe/cache');

module.exports = function(el, component, exe) {
  var Relay, _memory, _scene, _state, update;
  _scene = null;
  _memory = {};
  _state = layers();
  update = function() {
    if (_scene == null) {
      return Relay.mount();
    }
    return _scene.update(_state.get(), _memory);
  };
  cache = cache(exe);
  cache.on('ready', update);
  cache.on('result', _state.apply);
  Relay = {
    mount: function() {
      return _scene = component.mount(el, _state.get(), _memory);
    },
    update: function(params) {
      extend(_memory, params);
      return cache.run(component.query(_memory));
    },
    layer: _state.layer,
    params: function() {
      return _memory;
    },
    state: function() {
      return _state.get();
    },
    unmount: function() {
      _scene.unmount();
      return _scene = null;
    }
  };
  return Relay;
};
