// Generated by CoffeeScript 1.9.1
var extend;

extend = require('extend');

module.exports = function(initialState) {
  var _layers, _state;
  _state = {};
  _layers = [];
  if (initialState != null) {
    extend(true, _state, initialState);
  }
  return {
    apply: function(diff) {
      return extend(true, _state, diff);
    },
    clear: function() {
      return _state = {};
    },
    get: function() {
      var i, layer, len, result;
      result = {};
      extend(result, _state);
      for (i = 0, len = _layers.length; i < len; i++) {
        layer = _layers[i];
        extend(true, result, layer);
      }
      return result;
    },
    layer: function(layer) {
      _layers.push(layer);
      return {
        rollback: function() {
          index(_layers.indexOf(layer));
          return _layers.splice(index, 1);
        },
        commit: function() {
          index(_layers.indexOf(layer));
          _layers.splice(index, 1);
          return extend(_state, layer);
        }
      };
    }
  };
};
