// Generated by CoffeeScript 1.9.2
var build, split;

split = require('odoql-exe/split');

build = require('odoql-exe/buildqueries');

module.exports = function(exe, component, params, hub, cb) {
  var queries, run;
  queries = component.query(params);
  queries = split(exe, queries);
  queries = queries.local;
  run = build(exe, queries);
  return run(function(err, state) {
    var html;
    if (err != null) {
      return cb(err);
    }
    html = component.stringify(state, params, hub);
    return cb(null, {
      hub: hub,
      params: params,
      queries: queries,
      state: state,
      html: html
    });
  });
};
