// Generated by CoffeeScript 1.8.0
var relay;

relay = require('./relay');

module.exports = function(component, spec) {
  if (spec.query == null) {
    return;
  }
  return component.relay = function(el, stores) {
    return relay(el, component, stores);
  };
};
